export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SALES = "GET_SALES";
export const RESTORE_STATE = "RESTORE_STATE";
export const SHOW_PRODUCT_MODAL = "SHOW_PRODUCT_MODAL";
export const REORDER_PRODUCTS = "REORDER_PRODUCTS";
export const NEW_STOCK_PRODUCTS = "NEW_STOCK_PRODUCTS";
